### ISSUE TITLE
file paths parsing not consistent

### ISSUE THREAD

**Issue by nashmit** [clemense/yourdfpy#27]
Currently, this project works well under Linux but not under Windows.

This is due to the fact that the separators are mixed into the parsing process. If the urdf file contains Linux separators "/" to define paths one will end up mixing Linux sep. with windows since in the current implementation os.path.sep is used, which in this case it's going to return `\\.`

Can you advise an easy fix at this point?

**Comment by clemense** [comment]
Thanks for reporting!  As far as I understand I assume a file name prefix like `package://` would look like `package:\\` in Windows which is not the case, right?  (I couldn't find any information on this).  I will create a fix for this.

**Comment by clemense** [comment]
Ok, I hope this fixes it. It's now in version 0.0.51.  Please re-open if this still occurs.

**Comment by nashmit** [comment]
Thanks for taking care of it :)
