### ISSUE TITLE
dae format not supported

### ISSUE THREAD

**Issue by nashmit** [clemense/yourdfpy#29]
I've tried to reproduce your tests but, for some reason, it doesn't work out of the box.

You are mentioning this repo: https://github.com/ankurhanda/robot-assets as robots test input. 

The problem is that some of the robots are using ".dae" format for geometry which "trimesh" doesn't accept as input. I guess you didn't change manually the mesh geometry format for those robots, right?

**Comment by clemense** [comment]
Thanks for reporting!
Trimesh does support loading Collada meshes (.dae), it uses pycollada under the hood. But it requires the installation of `trimesh[easy]` (instead of `trimesh`, see https://trimsh.org/install.html). I will update the dependencies accordingly!

**Comment by clemense** [comment]
Alright, this is now in version v0.0.52. Please re-open if this is still an issue.
