### ISSUE TITLE
CrazyFlie2 COLLADA mesh not loaded properly

### ISSUE THREAD

**Issue by stephane-caron** [clemense/yourdfpy#37]
I'm not sure whether the issue comes from yourdfpy or one of its dependencies, but the [CrazyFlie2 URDF](https://github.com/utiasDSL/gym-pybullet-drones/blob/2c2470c2043eb4cf474d9af2681c9fa10f2d0e2f/gym_pybullet_drones/assets/cf2p.urdf) does not load properly.

The URDF has a single Collada mesh, here it is loaded by Blender (left) and yourdfpy 0.0.52 (right):

![image](https://user-images.githubusercontent.com/1189580/184337268-510e8b4c-7a38-40ac-b18e-d01600b4e98d.png)

In yourdfpy, three out of four propellers are missing.

**Comment by clemense** [comment]
I can't really reproduce this error. The link above is not pointing to any URDF. What's the URDF in question?

I tried it with https://github.com/utiasDSL/gym-pybullet-drones/tree/master/gym_pybullet_drones/assets and both cf2x.urdf and cf2p.urdf look fine in the current yourdfpy version:

![Screenshot from 2023-12-17 00-43-21](https://github.com/clemense/yourdfpy/assets/1800546/14046423-b224-48bc-81ea-3d7df256ef2d)
![Screenshot from 2023-12-17 00-42-59](https://github.com/clemense/yourdfpy/assets/1800546/474e68fa-6cc8-447d-ae35-c5fa9e5b4465)

**Comment by stephane-caron** [comment]
Sorry for the missing link, the URDF was indeed [the one from gym-pybullet-drones](https://github.com/utiasDSL/gym-pybullet-drones/blob/7688e72/gym_pybullet_drones/assets/cf2p.urdf).

I just tried again with the latest versions and it works :+1:
