### ISSUE TITLE
Independent axis scaling

### ISSUE THREAD

**Issue by stephane-caron** [clemense/yourdfpy#41]
Some URDFs, like the [TALOS robot description](https://github.com/stack-of-tasks/talos-data/), use `[1 -1 1]` axis scales to flip meshes. Here is how the model looks with *yourdfpy*: the robot's right leg is flipped, warnings in the terminal explain why:

![image](https://user-images.githubusercontent.com/1189580/188086126-cc3e9f75-f464-4abc-8174-de3da0500871.png)

Would it be possible for *yourdfpy* to support that part of the standard?

**Comment by clemense** [comment]
Supported in latest release (v0.0.55)
