### ISSUE TITLE
missing pyglet

### ISSUE THREAD

**Issue by TontonTremblay** [clemense/yourdfpy#47]
pyglet not getting installed while setup.py 

```
pip install pyglet==1.5.27
```
Need older version for trimesh. https://github.com/mikedh/trimesh/blob/main/trimesh/viewer/windowed.py#L21

**Comment by ghuber-github** [comment]
i had the same issue. fyi: on another machine i got a, so the version requirement should perhaps be fixed:
` ImportError: 'trimesh.viewer.windowed' requires 'pip install "pyglet<2"' `

**Comment by clemense** [comment]
Fixed in latest release (v0.0.55). This will now be installed by `pip install yourdfpy[full]`. (without the `[full]` option pyglet<2.0 won't be a dependency)
