### ISSUE TITLE
Release v0.0.55 to PyPI

### ISSUE THREAD

**Issue by stephane-caron** [clemense/yourdfpy#53]
The last two releases of yourdfpy, v0.0.54 and v0.0.55, have not been uploaded to PyPI. @clemense Would it be possible to push them?

This would unblock https://github.com/robot-descriptions/robot_descriptions.py/pull/51

**Comment by clemense** [comment]
Thanks for noticing!  The travis pipeline stopped working. I just switched to Github Actions. The latest version is v0.0.56 (it's identical to v0.0.55).
