### ISSUE TITLE
Apply visual colors

### ISSUE THREAD

**Issue by stephane-caron** [clemense/yourdfpy#7]
If I understand correctly, visual materials are currently read and written but not rendered. Loading e.g. the [Upkie](https://github.com/tasts-robots/upkie_description) URDF we get the dark "ninja" version:

![upkie-ninja](https://user-images.githubusercontent.com/1189580/161933384-6c3c4731-8f60-46b8-aaac-389817d6cbb1.png)

Trimesh can render materials so getting them to yourdfpy is a matter of plugging the right info. Here is for instance a [draft PR](https://github.com/clemense/yourdfpy/pull/6) to do so (opening the issue here to keep track):

![upkie-colored-chassis](https://user-images.githubusercontent.com/1189580/161933563-0bc41275-c283-4653-bf53-dd96d6f21076.png)

Is there an interest to render colors (eventually materials) in yourdfpy?

**Comment by clemense** [comment]
Oh, that's great, thanks!  What do you think is missing to make this a non-draft PR?

**Comment by stephane-caron** [comment]
Well I hacked the call to `apply_visual_color(geom, v)` at the first spot I found where it worked, so first I wanted your feedback on whether it makes sense within the overall code :smiley: 

There are three aspects to materials from the [URDF reference](https://wiki.ros.org/urdf/XML/link#Elements) that a visualizer would eventually need to handle: color, texture and named material.

If it makes sense, we could go for it this way:

- Color: this PR
- Named materials: subsequent PR (probably more involved, with updates to `Robot` and `_parse_robot`)
- Texture: later (not part of my current use cases but likely useful to others)

**Comment by stephane-caron** [comment]
And https://github.com/clemense/yourdfpy/pull/15 adds support for named materials, so now the Upkie model renders as:

![image](https://user-images.githubusercontent.com/1189580/165987233-f7362f8f-5a2e-49f7-a670-55d4e85ea139.png)

Moving the remaining point on textures to https://github.com/clemense/yourdfpy/issues/16 so that we can let the PR close this issue.
